[package]
name = "ros_rust"
version = "0.2.0"
authors = [ "Jon Binney <jon.binney@gmail.com>", "Jackie Kay <jacquelinekay1@gmail.com" ]

[dependencies]
regex = "0.1.41"
regex_macros = "0.1.21"
log = "0.3"
threadpool = "0.1.4"
